In [3]:
import dash 
from jupyter_dash import JupyterDash
from dash import html 
from dash import dcc

In [4]:
import plotly.express as px

In [5]:
df = px.data.gapminder()
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [6]:
 fig = px.scatter(df, x ='gdpPercap', y ='lifeExp' ,color = 'continent',width =1500,height= 750,title='my chart',
           size = 'pop', hover_name='country',log_x=True,
           size_max=60,symbol='continent', animation_frame='year',template = 'plotly_dark')

In [13]:
import dash
from dash import html
from dash import dcc
from dash.dependencies import Input,Output
from numpy.core.numeric import outer
import plotly.express as px
import pandas as pd

app=dash.Dash()

df=px.data.gapminder()


app.layout=html.Div([

                        html.H1('Call back Example 2', style={'textAlign':'center'}),
                        dcc.Graph(id='myGraph', figure={}),
                        dcc.Slider(
                                    id='my-slider',
                                    min=df['year'].min(),
                                    max=df['year'].max(),
                                    value=df['year'].min(),
                                    step=None,
             marks={str(years):str(years) for years in df['year'].unique()}
        )

])

@app.callback(
    Output('myGraph','figure'),
    Input('my-slider','value'))
def update_graph(slidervalue):
    filtered_df=df[df.year==slidervalue]
    fig=px.scatter(filtered_df,x="gdpPercap", y="lifeExp", size="pop", color="continent")
    return fig


if __name__=='__main__':
    app.run_server(debug=True)

SyntaxError: invalid syntax (<ipython-input-13-91924a399f63>, line 9)